"""EvidenceTracer — trace a score back to its data sources through the graph.

The core question: "Where did this +45 come from?" — answer by walking
upstream edges from the score node. Upstream in Phase 3A is:
  - INFLUENCES / DERIVED_FROM  (Score -> Score, cross-layer)
  - CONTRIBUTES_TO            (Signal -> Score, but we walk the *inverse*:
                                Score -> Signal when following evidence)
  - GENERATED                 (Signal -> Source, again inverse:
                                Signal -> Source)
  - CITES                     (Score -> Source)

We don't actually need an "inverse" edge in the graph: the same edge
record can be traversed backwards by following direction="in".
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

from phase3.datamodel.graph import EdgeType, GraphNode
from phase3.graph.in_memory_store import GraphStore
from phase3.graph.traversal import bfs


# Edge types that are evidence-relevant (i.e. trace away from the score).
EVIDENCE_UPSTREAM_EDGE_TYPES: list[EdgeType] = [
    EdgeType.DERIVED_FROM,    # this score was derived from another
    EdgeType.INFLUENCES,      # this score was influenced by another
    EdgeType.CONTRIBUTES_TO,  # a signal contributed to this score
    EdgeType.CITES,           # the score cites a source
    EdgeType.GENERATED,       # a signal was generated by a source
    EdgeType.EXPOSED_TO,      # the company is exposed to a macro factor
    EdgeType.REFERS_TO,       # a news node refers to an entity
]

EVIDENCE_DOWNSTREAM_EDGE_TYPES: list[EdgeType] = [
    EdgeType.INCLUDES,         # a report includes this score
    EdgeType.INFLUENCES,       # this score influenced downstream scores
    EdgeType.DERIVED_FROM,     # downstream scores derived from this
]


@dataclass(frozen=True)
class EvidenceChain:
    """A trace result: ordered list of (hop, node) pairs from the start
    to the leaf (data source) nodes.
    """

    start: str
    nodes: list[GraphNode] = field(default_factory=list)
    edges: list[Any] = field(default_factory=list)
    leaf_node_ids: list[str] = field(default_factory=list)
    truncated: bool = False

    def to_text(self, max_lines: int = 50) -> str:
        """Render a human-readable trace."""
        lines: list[str] = [f"trace start: {self.start}"]
        if self.truncated:
            lines.append("(truncated at max_depth)")
        for n in self.nodes[:max_lines]:
            lines.append(f"  • {n.node_type.value}: {n.label}  ({n.node_id})")
        if len(self.nodes) > max_lines:
            lines.append(f"  … and {len(self.nodes) - max_lines} more")
        if self.leaf_node_ids:
            leaf_types: dict[str, int] = {}
            for nid in self.leaf_node_ids:
                n = self.nodes_dict().get(nid)
                if n is None:
                    continue
                leaf_types[n.node_type.value] = leaf_types.get(n.node_type.value, 0) + 1
            summary = ", ".join(f"{k}×{v}" for k, v in sorted(leaf_types.items()))
            lines.append(f"leaf summary: {summary}")
        return "\n".join(lines)

    def nodes_dict(self) -> dict[str, GraphNode]:
        return {n.node_id: n for n in self.nodes}


class EvidenceTracer:
    """Trace a score or signal back to its sources."""

    def __init__(self, store: GraphStore) -> None:
        self._store = store

    def trace(
        self,
        start_node_id: str,
        max_depth: int = 5,
        direction: Literal["upstream", "downstream"] = "upstream",
        edge_types: list[EdgeType] | None = None,
    ) -> EvidenceChain:
        if not self._store.has_node(start_node_id):
            return EvidenceChain(
                start=start_node_id, truncated=False, leaf_node_ids=[],
            )
        if edge_types is None:
            edge_types = (
                EVIDENCE_UPSTREAM_EDGE_TYPES
                if direction == "upstream"
                else EVIDENCE_DOWNSTREAM_EDGE_TYPES
            )
        # "Upstream" means we want to follow the *incoming* edges of the
        # start node (i.e. nodes that point TO this one). That's BFS
        # direction="in". Same for downstream except direction="out".
        bfs_dir: Literal["in", "out"] = "in" if direction == "upstream" else "out"
        reached = bfs(
            self._store,
            start=start_node_id,
            max_depth=max_depth,
            edge_types=edge_types,
            direction=bfs_dir,
        )
        # The first reached nodes are depth 1, so BFS order is hop order.
        # Identify leaves: a node is a "leaf" if it has no further upstream
        # evidence edges (or if we hit the depth limit).
        leaves: list[str] = []
        for n in reached:
            upstream = self._store.get_neighbors(
                n.node_id, edge_types=edge_types, direction="in",
            )
            if not upstream:
                leaves.append(n.node_id)
        return EvidenceChain(
            start=start_node_id, nodes=reached, edges=[], leaf_node_ids=leaves,
            truncated=len(reached) >= 1 and any(
                self._store.get_neighbors(
                    n.node_id, edge_types=edge_types, direction="in",
                ) for n in reached
            ),
        )


__all__ = ["EvidenceTracer", "EvidenceChain"]
